# Site settings
author: Alex Merecka
title: My Journey to Becoming a Web Developer
header-img: img/home-bg.png
email: merecka@gmail.com
copyright_name: Alex Merecka
description: > # this means to ignore newlines until "baseurl:"
  Journey into Web Development
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  merecka

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
